source "https://rubygems.org"

git_source(:github) {|movie-finder| "https://github.com/#{movie-finder}" }

# Specify your gem's dependencies in movie-finder.gemspec
```ruby
gem 'movie-finder'
```
gemspec
